export type Product = { category: string; name: string; description: string; audience: string; includes: string[] };

export const products: Product[] = [
  { category: "Planos de Saúde", name: "Individual", description: "Um plano escolhido para sua rotina, região e prioridades de cuidado.", audience: "Para quem busca proteção para si.", includes: ["Rede de atendimento conforme o plano", "Consultas e exames previstos no contrato", "Opções de acomodação e abrangência"] },
  { category: "Planos de Saúde", name: "Familiar Empresarial", description: "Cuidado para sua família por meio de uma contratação empresarial elegível.", audience: "Para famílias vinculadas a uma empresa.", includes: ["Cobertura para dependentes elegíveis", "Comparação de redes e abrangências", "Orientação na contratação"] },
  { category: "Planos de Saúde", name: "Coletivo Empresarial", description: "Saúde como benefício para atrair e cuidar da equipe.", audience: "Para empresas de diferentes portes.", includes: ["Planos para colaboradores", "Opções de rede e coparticipação", "Apoio na implantação e gestão"] },
  { category: "Planos de Saúde", name: "Seguro Odonto", description: "Acesso planejado a cuidados odontológicos.", audience: "Para pessoas, famílias e equipes.", includes: ["Consultas e procedimentos contratados", "Rede credenciada conforme o plano", "Opções individuais e coletivas"] },
  { category: "Seguros para Empresas", name: "Empresarial", description: "Proteção para o patrimônio e a continuidade do negócio.", audience: "Para comércio, serviços e indústria.", includes: ["Incêndio e danos ao imóvel", "Equipamentos e conteúdo", "Coberturas opcionais para operação"] },
  { category: "Seguros para Empresas", name: "Agronegócios", description: "Soluções para riscos do campo e da produção.", audience: "Para produtores e empresas do agro.", includes: ["Riscos rurais conforme a modalidade", "Bens e estruturas", "Máquinas e equipamentos"] },
  { category: "Seguros para Empresas", name: "Máquinas e Equipamentos", description: "Proteção para ativos essenciais à operação.", audience: "Para quem depende de máquinas para produzir.", includes: ["Danos aos equipamentos", "Roubo ou furto qualificado conforme apólice", "Opções para operação e transporte"] },
  { category: "Seguros para Empresas", name: "Responsabilidade Civil", description: "Apoio diante de danos involuntários causados a terceiros.", audience: "Para empresas e profissionais.", includes: ["Danos materiais a terceiros", "Danos corporais previstos na apólice", "Modalidades específicas da atividade"] },
  { category: "Seguros para Empresas", name: "Condomínio e Imobiliária", description: "Coberturas para edifícios, administração e locação.", audience: "Para condomínios, síndicos e imobiliárias.", includes: ["Estrutura e áreas comuns", "Responsabilidades contratadas", "Soluções para imóveis e locações"] },
  { category: "Seguros para Empresas", name: "Eventos", description: "Planejamento de riscos para o evento acontecer com mais tranquilidade.", audience: "Para organizadores e produtores.", includes: ["Responsabilidade civil do evento", "Estruturas e equipamentos", "Coberturas ajustadas ao formato"] },
  { category: "Seguros para Empresas", name: "Transportes", description: "Proteção para mercadorias durante o deslocamento.", audience: "Para embarcadores e transportadores.", includes: ["Carga transportada", "Riscos conforme rota e modal", "Coberturas complementares"] },
  { category: "Seguros para Empresas", name: "Seguro de Vida Empresarial", description: "Um benefício de proteção financeira para a equipe.", audience: "Para empresas que cuidam de seus colaboradores.", includes: ["Morte e invalidez conforme contrato", "Assistências opcionais", "Condições para grupos elegíveis"] },
  { category: "Seguros para Pessoas", name: "Automóvel", description: "Escolha coberturas adequadas ao seu carro e ao seu uso.", audience: "Para proprietários de veículos.", includes: ["Colisão, roubo e furto conforme plano", "Responsabilidade civil", "Assistência e carro reserva opcionais"] },
  { category: "Seguros para Pessoas", name: "Vida", description: "Proteção financeira para quem depende de você.", audience: "Para pessoas e famílias.", includes: ["Cobertura por morte", "Invalidez e doenças graves opcionais", "Assistências conforme contratação"] },
  { category: "Seguros para Pessoas", name: "Residência", description: "Mais segurança para o imóvel e o que está dentro dele.", audience: "Para proprietários e moradores.", includes: ["Incêndio e danos contratados", "Roubo e danos elétricos opcionais", "Assistência residencial conforme plano"] },
  { category: "Seguros para Pessoas", name: "Viagem", description: "Apoio para imprevistos longe de casa.", audience: "Para viagens nacionais e internacionais.", includes: ["Despesas médicas conforme plano", "Bagagem e atraso opcionais", "Assistência durante a viagem"] },
  { category: "Seguros para Pessoas", name: "Bike e Eletrônicos", description: "Proteção para bens que acompanham seu dia.", audience: "Para ciclistas e usuários de eletrônicos.", includes: ["Danos acidentais conforme apólice", "Roubo ou furto qualificado", "Coberturas adicionais disponíveis"] },
  { category: "Seguros para Pessoas", name: "Equipamentos Portáteis", description: "Coberturas para equipamentos que você leva ao trabalho e à rotina.", audience: "Para profissionais e usuários de dispositivos.", includes: ["Danos acidentais", "Roubo ou furto qualificado", "Proteção em deslocamentos conforme contrato"] },
  { category: "Serviços Financeiros", name: "Consórcio", description: "Planeje uma conquista com parcelas e regras conhecidas.", audience: "Para quem pode se planejar no médio ou longo prazo.", includes: ["Cartas de crédito disponíveis", "Prazos e parcelas", "Orientação sobre contemplação"] },
  { category: "Serviços Financeiros", name: "Empréstimo com Garantia", description: "Avalie crédito usando um bem como garantia.", audience: "Para quem busca crédito e possui bem elegível.", includes: ["Análise de condições", "Prazos e taxas conforme proposta", "Orientação sobre riscos e garantia"] },
  { category: "Serviços Financeiros", name: "Financiamento de Veículo", description: "Compare condições para comprar seu veículo com crédito.", audience: "Para quem está adquirindo um veículo.", includes: ["Simulação de parcelas", "Análise de taxas e prazo", "Orientação até a contratação"] },
];

export const categories = ["Planos de Saúde", "Seguros para Empresas", "Seguros para Pessoas", "Serviços Financeiros"];
